/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * msg.java
 *
 * Created on Nov 19, 2016, 4:01:23 PM
 */
package dnafinal;

import java.math.BigInteger;

/**
 *
 * @author ACER
 */
public class msg extends javax.swing.JFrame {

    /** Creates new form msg */
    public msg() {
        initComponents();
         pnl3.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnDecrypt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtDNADigitalCode2 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtBinaryValue2 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtHexadecimal2 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        txtAsciiValue2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));

        txtMsg.setEditable(false);
        txtMsg.setColumns(20);
        txtMsg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtMsg.setRows(5);
        jScrollPane1.setViewportView(txtMsg);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Message :");

        btnDecrypt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDecrypt.setText("Decrypt");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Click on Decrypt To View Message");

        pnl3.setBackground(new java.awt.Color(255, 204, 255));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel14.setText("Original Text:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel15.setText("DNA Digital Code:");

        txtDNADigitalCode2.setEditable(false);
        txtDNADigitalCode2.setBackground(new java.awt.Color(0, 0, 0));
        txtDNADigitalCode2.setColumns(20);
        txtDNADigitalCode2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDNADigitalCode2.setForeground(new java.awt.Color(255, 255, 255));
        txtDNADigitalCode2.setRows(5);
        txtDNADigitalCode2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtDNADigitalCode2.setEnabled(false);
        jScrollPane14.setViewportView(txtDNADigitalCode2);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel16.setText("Binary:");

        txtBinaryValue2.setEditable(false);
        txtBinaryValue2.setBackground(new java.awt.Color(0, 0, 0));
        txtBinaryValue2.setColumns(20);
        txtBinaryValue2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtBinaryValue2.setForeground(new java.awt.Color(255, 255, 255));
        txtBinaryValue2.setRows(5);
        txtBinaryValue2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtBinaryValue2.setEnabled(false);
        jScrollPane15.setViewportView(txtBinaryValue2);

        txtHexadecimal2.setEditable(false);
        txtHexadecimal2.setBackground(new java.awt.Color(0, 0, 0));
        txtHexadecimal2.setColumns(20);
        txtHexadecimal2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtHexadecimal2.setForeground(new java.awt.Color(255, 255, 255));
        txtHexadecimal2.setRows(5);
        txtHexadecimal2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtHexadecimal2.setEnabled(false);
        jScrollPane16.setViewportView(txtHexadecimal2);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel17.setText("Hexadecimal:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel18.setText("ASCII:");

        txtAsciiValue2.setEditable(false);
        txtAsciiValue2.setBackground(new java.awt.Color(0, 0, 0));
        txtAsciiValue2.setColumns(20);
        txtAsciiValue2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAsciiValue2.setForeground(new java.awt.Color(255, 255, 255));
        txtAsciiValue2.setRows(5);
        txtAsciiValue2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtAsciiValue2.setEnabled(false);
        jScrollPane17.setViewportView(txtAsciiValue2);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(24, 24, 24)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel14))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(btnDecrypt))
                    .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDecrypt)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String binaryToHex(String bin) {
   String s = bin;
BigInteger b = new BigInteger(s, 2);
System.out.println(b.toString(16));
String value=b.toString(16);
   //  return Long.toHexString(Long.parseLong(bin,2));
     //return String.format("%X", Long.parseLong(bin,2)) ;
 //return String.format("%X", Long.parseLong(bin,2)) ;
//    return String.format("%02X", Long.parseUnsignedLong(bin,2)) ;
return value;
}

/*
public static String binary_to_hex(String binary) {
    String hex = "";
    String hex_char;
    int len = binary.length()/8;
    for(int i=0;i<len;i++){
        String bin_char = binary.substring(8*i,8*i+8);
        int conv_int = Integer.parseInt(bin_char,2);
        hex_char = Integer.toHexString(conv_int);
        if(i==0) hex = hex_char;
        else hex = hex+hex_char;
    }
    return hex;
}*/

public String convertHexToString(String hex){

	  StringBuilder sb = new StringBuilder();
	  StringBuilder temp = new StringBuilder();

	  //49204c6f7665204a617661 split into two characters 49, 20, 4c...
	  for( int i=0; i<hex.length()-1; i+=2 ){

	      //grab the hex in pairs
	      String output = hex.substring(i, (i + 2));
	      //convert hex to decimal
	      int decimal = Integer.parseInt(output, 16);
	      //convert the decimal to character
	      sb.append((char)decimal);

	      temp.append(decimal);
	  }
	  System.out.println("ASCII : " + temp.toString());
txtAsciiValue2.setText(temp.toString());
	  return sb.toString();
  }
    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
        String msg=txtMsg.getText().trim();
       btnDecrypt.setEnabled(false);
        pnl3.setVisible(true);
        String b;
        String sum="";
        
         for (int i = 0; i < msg.length(); i = i + 4)
            {
                // mList.Add(binary.Substring(i, 2));
                b = msg.substring(i, i+4);
                if ("0101".equals(b))
                {
                    b = "AA";

                }
                else if ("0010".equals(b))
                {
                    b = "AC";
                }

                else if ("0011".equals(b))
                {
                    b = "AT";
                }
                else if ("0001".equals(b))
                {
                    b = "AG";
                }
                else if ("0110".equals(b))
                {
                    b = "TA";
                }
                else if ("1111".equals(b))
                {
                    b = "TT";
                }
                else if ("0111".equals(b))
                {
                    b = "TG";
                }
                else if ("1001".equals(b))
                {
                    b = "TC";
                }
                else if ("1010".equals(b))
                {
                    b = "GA";
                }
                else if ("0100".equals(b))
                {
                    b = "GT";
                }
                else if ("0100".equals(b))
                {
                    b = "GG";
                }
                else if ("1100".equals(b))
                {
                    b = "GC";
                }
                else if ("1110".equals(b))
                {
                    b = "CA";
                }
                else if ("1011".equals(b))
                {
                    b = "CT";
                }
                else if ("0000".equals(b))
                {
                    b = "CG";
                }
                else if ("1101".equals(b))
                {
                    b = "CC";
                }
                sum += b;
            }
         System.out.println("sum Value: "+sum);
    txtDNADigitalCode2.setText(sum);
         String a;
         String sum1="";
          System.out.println("dna");
         for (int i = 0; i < sum.length(); i = i + 1)
            {
                // mList.Add(binary.Substring(i, 2));
                a = sum.substring(i, i+1);

                if ("T".equals(a))
                {
                    a = "01";
                }
                else if ("A".equals(a))
                {
                    a = "00";
                }
                else if ("G".equals(a))
                {
                    a = "10";
                }
                else if ("C".equals(a))
                {
                    a = "11";
                }

                sum1 += a;
            }
          System.out.println("Sum1 value: "+sum1);
          txtBinaryValue2.setText(sum1);
           String bin2;
//            if (sum1.length() % 2 != 0)
//            {
//                bin2 = sum1;
//            }
//            else
//            {
//               // bin2 = sum1.trim();
//               
//                bin2=sum1.substring(0, sum1.length()-1);
//            }
//            System.out.println(bin2);
           // String hexxa=binary_to_hex(bin2);
               //System.out.println(hexxa);
            String hex=binaryToHex(sum1);
            txtHexadecimal2.setText(hex);
           System.out.println("hex value: "+hex);
            String mssg=convertHexToString(hex.trim());
            System.out.println("msg"+mssg);
            jTextArea1.setText(mssg);
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           getRootPane().getParent().setVisible(false);
        txtMsg.setText("");
        jTextArea1.setText("");
        Home h=new Home();
        h.setVisible(true);
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new msg().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnl3;
    private javax.swing.JTextArea txtAsciiValue2;
    private javax.swing.JTextArea txtBinaryValue2;
    private javax.swing.JTextArea txtDNADigitalCode2;
    private javax.swing.JTextArea txtHexadecimal2;
    public javax.swing.JTextArea txtMsg;
    // End of variables declaration//GEN-END:variables
}
