/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * outbox.java
 *
 * Created on Nov 21, 2016, 11:03:46 AM
 */
package dnafinal;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.sql.ResultSet;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author ACER
 */
public class outbox extends javax.swing.JPanel {
DefaultTableModel dm; 
    /** Creates new form outbox */
    public outbox() {
        initComponents();
          setTable();  
     getdata();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
     msg jn=new msg();
    private void setTable() {  
     dm = new DefaultTableModel(0, 0);  
     String s[] = new String[]{"Id","Subject", "Receiver","Date","Time","Text"};  
     dm.setColumnIdentifiers(s); 
     
       
     jTable1.setModel(dm);  
      
   }  
      private void getdata() {  
          
     //Connection con;  
       try {  
           String uname=Login.uname1;
                  
       ResultSet rs = DataBase.getMessage(uname);
       while (rs.next()) {  
          String id = rs.getString("r_id");  
          String subj = rs.getString("subject");  
         String send = rs.getString("receiver");  
         String date = rs.getString("senddate"); 
         String time = rs.getString("sendtime");
         String ms = rs.getString("message");
         Vector<String> vector = new Vector<String>();  
         //     vector.add(name);  
         vector.add(id);  
         vector.add(subj);  
         vector.add(send);
         vector.add(date);
         vector.add(time);
         vector.add(ms);
         dm.addRow(vector);  
       }  
     } catch (Exception ex) {  
     //  Logger.getLogger(JdefaluttableDemo.class.getName()).log(Level.SEVERE, null, ex);  
     }
      
   } 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         getRootPane().getParent().setVisible(false);
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String name=model.getValueAt(index, 5).toString();
        jn.setVisible(true);
        jn.pack();
        jn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jn.txtMsg.setText(name);
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
